steps:
  - id: "Executando Instalação"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['install', 'app']
    env: ['GOPATH=.']

  - id: "Executando testes"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', 'app']
    env: ['GOPATH=.']