apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hpa-app
  template:
    metadata:
      labels:
        app: go-hpa-app
    spec:
      containers:
      - name: go-hpa-app
        image: vhsilva/go-hpa:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"