apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-hpa-app
  targetCPUUtilizationPercentage: 15